Develop
NatalieFilippi/java-filmorate pull request #21
Opened 2022-07-27 22:08 UTC by NatalieFilippi

2022-07-28 22:42 UTC, alexache requested changes
Очень не хватает списка реализованного функционала где-то в ридми или в комментарии к пулл реквесту, Остальные комментарии по коду

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            if (initFilm.getDirectors().size() != 0 && updFilm.getDirectors().size() == 0) {
Немного непонятная проверка - а что если филь обновляется, но режисер уже не был указан, то эта часть с обнулением уже не нужна?

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Film makeFilmBySort(ResultSet rs, int rowNum) throws SQLException {
Почему этот метод отличается от соседнего? В общем случае не нужны жанры?

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam Map<String, String> params)
Странный выбор, почему не отдельными параметрами 2 новых параметра?

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    public Optional<List<Film>> findCommonFilms(long userId, long friendId) throws ObjectNotFoundException {
Точно ли здесь нужен Optional? Разве нужно отличать пустой лист от несуществующего листа (возможен ли такой?)

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        List<Object> values = new ArrayList<>();
Использование Object всегда вызывает вопросы, почему не использовать коллекцию строк? Можно ведь все в строки сконвертировать для sql query

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (int i = 0; i < conditions.size(); i++) {
Мне кажется, что можно было бы обойтись без такого шага и использовать только стрингбилдер, а необходимость AND проверять при налачие фильтра по году после фильтра по жанру (по values например). С другой стороны, если прдполагать что фильтров может быть больше, то ок, правка не нужна

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (searchOptions.size() > new HashSet<>(searchOptions).size()) {
Оригинально!

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            if (!(i == searchOptions.size() - 1)) sb.append(" UNION ");
Как-то сложно, может можно обойтись одним сформированным sql select запросом?

2022-07-28 22:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataNotFoundException.java
> +public class DataNotFoundException extends RuntimeException {
Есть ли отличие по смыслу от ObjectNotFoundException

2022-07-29 07:13 UTC, alex-pergushev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            if (initFilm.getDirectors().size() != 0 && updFilm.getDirectors().size() == 0) {
Данная проверка нужна для прохождения теста postman - Film update remove director, который ждет для директора вместо [] - null (pm.expect(jsonData.directors).null).

2022-07-29 07:28 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        List<Object> values = new ArrayList<>();
Да, исправим. Почему-то мне показалось, что в аргументы query() будет безопаснее передавать массив объектов, чем строк

2022-07-29 07:29 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (int i = 0; i < conditions.size(); i++) {
Действительно, это делалось с прицелом на расширяемость и добавление новых фильтров в будущем.

2022-07-29 07:29 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (searchOptions.size() > new HashSet<>(searchOptions).size()) {
Спасибо :)

2022-07-29 07:31 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            if (!(i == searchOptions.size() - 1)) sb.append(" UNION ");
Я думал о том, чтобы сделать это цельным запросом. Но все же пришел к выводу, что для расширяемости стоит сделать так, через UNION. В случае добавления новых фильтров - нам всего лишь понадобится добавить новую часть подзапроса и блок if. В противном случае - пришлось бы каждый раз править один большой запрос.

2022-07-29 07:35 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam Map<String, String> params)
Мар с параметрами предусмотрена для удобства и расширяемости в том случае, если опций фильтрации в будущем станет больше.

2022-07-29 07:37 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Film makeFilmBySort(ResultSet rs, int rowNum) throws SQLException {
Это странно, но данный метод был убран, и в ветке develop я его не вижу. Возможно произошла накладка с ветками.

2022-07-29 07:56 UTC, Noire86 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        List<Object> values = new ArrayList<>();
Исправлено в [31a3be9](https://github.com/NatalieFilippi/java-filmorate/pull/21/commits/31a3be9ed7dc5e92ebbe888e7723d8b1d2b110cb)

2022-07-29 10:49 UTC, Latarho commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        reviewService.addLikeReview(reviewId, userId);
Логирование добавлено.

2022-07-29 11:56 UTC, Latarho commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validationReview(getById(reviewId));
Удалено.

2022-07-29 11:56 UTC, Latarho commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        int useful = reviewStorage.getById(reviewId).getUseful();
Удалено.

2022-07-29 14:04 UTC, Latarho commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        return jdbcTemplate.query(SQL_GET_REVIEWS_FOR_FILM, (this::makeReview), filmId, count).stream()
сортировка вынесена в SQL запрос.

2022-07-29 14:28 UTC, Latarho commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataNotFoundException.java
> +public class DataNotFoundException extends RuntimeException {
DataNotFound удалил.

2022-07-29 19:17 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam Map<String, String> params)
Да. но ухудшает читаемость "интерфейса" REST слоя. Предположим, захотите документировать API и мапа параметров в интерфейсе некоторый черный ящик, пользователь API может передавать что угодно и спринг не поможет с валидацией параметров

2022-07-29 19:28 UTC, alexache approved these changes
Спасибо за исправления!

2022-07-29 19:42 UTC, merged